# Generated by Django 3.2.9 on 2022-08-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_footprint_room_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='test',
            field=models.JSONField(default=list),
        ),
    ]
