# Generated by Django 3.2.9 on 2022-08-06 02:52

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_target_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='test',
            field=models.JSONField(default=list, validators=[profiles.models.ChoiceValidator(['1', '2'])]),
        ),
    ]
