# Generated by Django 3.2.9 on 2022-08-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_target_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='age',
        ),
        migrations.RemoveField(
            model_name='target',
            name='country',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='target',
            name='test',
        ),
    ]
