# Generated by Django 3.2.9 on 2021-11-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dummy',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
