# Generated by Django 3.2.9 on 2021-11-25 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='d_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
