# Generated by Django 3.2.9 on 2021-11-25 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
