# Generated by Django 3.2.9 on 2021-11-26 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20211126_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='d_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
