# Generated by Django 3.2.9 on 2021-11-26 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20211126_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='d_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False, serialize=False),
        ),
    ]
