# Generated by Django 3.2.9 on 2021-11-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20211126_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='d_id',
            new_name='id',
        ),
    ]
