# Generated by Django 3.2.9 on 2021-11-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20211126_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
