# Generated by Django 3.2.9 on 2021-12-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20211126_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
