# Generated by Django 3.2.9 on 2022-01-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_profile_tz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tz',
            new_name='my_timezone',
        ),
    ]
