# Generated by Django 3.2.9 on 2022-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_auto_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
