# Generated by Django 3.2.9 on 2022-01-20 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20220120_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=170, primary_key=True, serialize=False),
        ),
    ]
