# Generated by Django 3.2.9 on 2022-02-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='warning',
            new_name='warning_text',
        ),
    ]
