# Generated by Django 3.2.9 on 2022-02-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20220215_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
