# Generated by Django 3.2.9 on 2022-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_profile_english_level_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, choices=[('20s', '20s'), ('30s', '30s'), ('40s', '40s'), ('50s', '50s'), ('60s', '60s'), ('70s or more', '70s or more')], max_length=20, null=True),
        ),
    ]
