# Generated by Django 3.2.9 on 2022-02-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20220216_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='politeness',
            field=models.CharField(blank=True, choices=[('3', 'polite'), ('2', 'normal'), ('1', 'a bit inpolite'), ('0', 'inpolite')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='punctuality',
            field=models.CharField(blank=True, choices=[('0', 'almost 0 min late'), ('5', 'around 5 mins late'), ('10', 'around 10 mins late'), ('15', 'around 15 mins or more late'), ('30', "didn't show up")], max_length=100, null=True),
        ),
    ]
