# Generated by Django 3.2.9 on 2022-02-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20220218_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy',
        ),
        migrations.AlterField(
            model_name='review',
            name='punctuality',
            field=models.CharField(blank=True, choices=[('no', "don't care"), ('0', 'almost 0 min late'), ('5', 'around 5 mins late'), ('10', 'around 10 mins late'), ('15', 'around 15 mins or later')], max_length=100, null=True),
        ),
    ]
