# Generated by Django 3.2.9 on 2022-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20220218_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certified',
        ),
    ]
