# Generated by Django 3.2.9 on 2022-02-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_remove_profile_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='politeness',
        ),
    ]
