# Generated by Django 3.2.9 on 2022-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_remove_review_politeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='politeness',
            field=models.CharField(blank=True, choices=[('3', 'polite'), ('2', 'normal'), ('1', 'a bit inpolite'), ('0', 'inpolite')], max_length=100, null=True),
        ),
    ]
