# Generated by Django 3.2.9 on 2022-02-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_review_politeness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
