# Generated by Django 3.2.9 on 2022-02-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.ImageField(null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ielts',
            field=models.CharField(blank=True, choices=[('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='toefl',
            field=models.CharField(blank=True, choices=[('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120')], max_length=200, null=True),
        ),
    ]
