# Generated by Django 3.2.9 on 2022-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_auto_20220219_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
