# Generated by Django 3.2.9 on 2022-02-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_profile_certified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_timezone',
            new_name='timezone',
        ),
    ]
