# Generated by Django 3.2.9 on 2022-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_rename_my_timezone_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certification',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
