# Generated by Django 3.2.9 on 2022-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_auto_20220223_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_age_reason',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_country_reason',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_sex_reason',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
