# Generated by Django 3.2.9 on 2022-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20220223_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certification_2',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification_3',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification_4',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
