# Generated by Django 3.2.9 on 2022-02-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20220223_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='certification',
            new_name='certification_ielts',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='certification_2',
            new_name='certification_toefl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certification_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certification_4',
        ),
    ]
