# Generated by Django 3.2.9 on 2022-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('Sports', 'Sports'), ('Religion', 'Religion'), ('Lifestyle', 'Lifestyle'), ('Hobby', 'Hobby'), ('Study', 'Study'), ('Dream', 'Dream'), ('Personality', 'Personality')], max_length=100)),
                ('profiles', models.ManyToManyField(blank=True, related_name='tags', to='profiles.Profile')),
            ],
        ),
    ]
