# Generated by Django 3.2.9 on 2022-03-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('review_title', models.CharField(blank=True, max_length=100)),
                ('review_text', models.TextField(blank=True, max_length=1000)),
                ('warning_title', models.CharField(blank=True, max_length=100)),
                ('warning_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('punctuality', models.CharField(blank=True, choices=[('no', "don't care"), ('0', 'almost 0 min late'), ('5', 'around 5 mins late'), ('10', 'around 10 mins late'), ('15', 'around 15 mins or later')], max_length=100, null=True)),
                ('politeness', models.CharField(blank=True, choices=[('3', 'polite'), ('2', 'normal'), ('1', 'a bit inpolite'), ('0', 'inpolite')], max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='profiles.profile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='profiles.profile')),
            ],
        ),
    ]
