# Generated by Django 3.2.9 on 2022-03-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_alter_room_open_time'),
        ('profiles', '0060_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'login'), ('search', 'search'), ('profile_page', 'profile_page'), ('room_page', 'room_page'), ('join', 'join')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='profiles.profile')),
                ('profile_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='profiles.profile')),
                ('room_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='rooms.room')),
            ],
        ),
    ]
