# Generated by Django 3.2.9 on 2022-03-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_footprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
            ],
            bases=('profiles.profile',),
        ),
    ]
