# Generated by Django 3.2.9 on 2022-03-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_alter_room_open_time'),
        ('profiles', '0063_delete_anonymousprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='profile_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='room_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='rooms.room'),
        ),
    ]
