# Generated by Django 3.2.9 on 2022-03-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_alter_room_open_time'),
        ('profiles', '0064_auto_20220311_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='kind',
            field=models.CharField(choices=[('login', 'login'), ('search', 'search'), ('profile_page', 'profile_page'), ('room_page', 'room_page'), ('join', 'join')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='profile_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='room_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='rooms.room'),
        ),
    ]
