# Generated by Django 3.2.9 on 2022-03-11 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0065_auto_20220311_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 11, 10, 19, 55, 272170, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
