# Generated by Django 3.2.9 on 2022-03-14 10:56

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0066_footprint_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_people',
            field=profiles.models.StringListField(blank=True, max_length='500', null=True),
        ),
    ]
