# Generated by Django 3.2.9 on 2022-03-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_profile_target_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Tech', 'Tech'), ('Religion', 'Religion'), ('Lifestyle', 'Lifestyle'), ('Hobby', 'Hobby'), ('Study', 'Study'), ('Dream', 'Dream'), ('Personality', 'Personality'), ('Self-help', 'Self-help'), ('Culture', 'Culture'), ('Job', 'Job')], max_length=100),
        ),
    ]
