# Generated by Django 3.2.9 on 2022-03-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0068_auto_20220314_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='politeness',
            field=models.CharField(blank=True, choices=[('3', 'polite'), ('2', 'normal'), ('1', 'a bit impolite'), ('0', 'impolite')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='warning_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Religion', 'Religion'), ('Lifestyle', 'Lifestyle'), ('Study', 'Study'), ('Dream', 'Dream'), ('Personality', 'Personality'), ('Self-help', 'Self-help'), ('Culture', 'Culture'), ('Job', 'Job')], max_length=100),
        ),
    ]
