# Generated by Django 3.2.9 on 2022-03-16 01:50

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0070_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='sex',
            field=profiles.models.MultipleChoiceableCharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
