# Generated by Django 3.2.9 on 2022-03-16 08:13

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0071_alter_target_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='sex',
            field=profiles.models.StringListField(blank=True, null=True),
        ),
    ]
