# Generated by Django 3.2.9 on 2022-03-20 05:09

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0072_alter_target_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='target_people',
        ),
        migrations.AddField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('TOEIC', 'TOEIC'), ('Linguaskill (Bulats)', 'Linguaskill (Bulats)'), ('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('DET (Duolingo English Test)', 'DET (Duolingo English Test)'), ('job interview practice', 'job interview practice'), ('conversation practice', 'conversation practice'), ('searching friends', 'searching friends')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_sex',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Religion', 'Religion'), ('Lifestyle', 'Lifestyle'), ('Study', 'Study'), ('Dream', 'Dream'), ('Personality', 'Personality'), ('Culture', 'Culture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='age',
            field=profiles.models.StringListField(blank=True, null=True, valid_choices=['20s', '30s', '40s', '50s', '60s', '70s or more']),
        ),
        migrations.AlterField(
            model_name='target',
            name='country',
            field=profiles.models.StringListField(blank=True, null=True, valid_choices=['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua & Deps', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Rep', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Congo {Democratic Rep}', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland {Republic}', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea North', 'Korea South', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar, {Burma}', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'St Kitts & Nevis', 'St Lucia', 'Saint Vincent & the Grenadines', 'Samoa', 'San Marino', 'Sao Tome & Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad & Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe']),
        ),
        migrations.AlterField(
            model_name='target',
            name='sex',
            field=profiles.models.StringListField(blank=True, null=True, valid_choices=['Female', 'Male']),
        ),
    ]
