# Generated by Django 3.2.9 on 2022-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0073_auto_20220320_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('TOEIC', 'TOEIC'), ('Linguaskill (Bulats)', 'Linguaskill (Bulats)'), ('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('DET (Duolingo English Test)', 'DET (Duolingo English Test)'), ('job interview practice', 'job interview practice'), ('conversation practice', 'conversation practice')], default='conversation practice', max_length=50),
        ),
    ]
