# Generated by Django 3.2.9 on 2022-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0074_alter_profile_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(choices=[('IELTS', 'IELTS'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('TOEIC', 'TOEIC'), ('Linguaskill (Bulats)', 'Linguaskill (Bulats)'), ('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('DET (Duolingo English Test)', 'DET (Duolingo English Test)'), ('job interview practice', 'job interview practice'), ('conversation practice', 'conversation practice')], default='conversation practice', max_length=50),
        ),
    ]
