# Generated by Django 3.2.9 on 2022-04-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0075_alter_profile_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
