# Generated by Django 3.2.9 on 2022-04-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0076_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='politeness',
        ),
    ]
