# Generated by Django 3.2.9 on 2022-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0077_remove_review_politeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
