# Generated by Django 3.2.9 on 2022-04-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0078_review_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='warning_title',
        ),
    ]
