# Generated by Django 3.2.9 on 2021-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_profile_followers'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='profiles.Profile'),
        ),
    ]
