# Generated by Django 3.2.9 on 2022-01-17 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from profiles.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_auto_timezone'),
        ('rooms', '0004_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owners',
        ),
        migrations.AddField(
            model_name='room',
            name='co_owners',
            field=models.ManyToManyField(related_name='co_owners', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(related_name='invited', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default='f7ab084d-7ed2-41eb-b5ec-45af162eeeab', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
