# Generated by Django 3.2.9 on 2022-01-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_auto_timezone'),
        ('rooms', '0005_auto_20220117_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='co_owner_invitation',
            field=models.ManyToManyField(related_name='co_owner_invitation', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='open_time',
            field=models.DateTimeField(null=True),
        ),
    ]
