# Generated by Django 3.2.9 on 2022-01-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220117_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='craeted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
