# Generated by Django 3.2.9 on 2022-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='appliable',
            field=models.BooleanField(default=True),
        ),
    ]
