# Generated by Django 3.2.9 on 2022-01-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_appliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reveal_owner',
            field=models.BooleanField(default=True),
        ),
    ]
