# Generated by Django 3.2.9 on 2022-01-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_alter_profile_id'),
        ('rooms', '0010_room_reveal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='applicants',
            field=models.ManyToManyField(null=True, related_name='applicants', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='co_owner_invitation',
            field=models.ManyToManyField(null=True, related_name='co_owner_invitation', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='co_owners',
            field=models.ManyToManyField(null=True, related_name='co_owners', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(null=True, related_name='invited', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='participants', to='profiles.Profile'),
        ),
    ]
