# Generated by Django 3.2.9 on 2022-02-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
