# Generated by Django 3.2.9 on 2022-02-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_rename_warning_review_warning_text'),
        ('rooms', '0014_alter_room_max_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='co_owner_invitation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='co_owners',
        ),
        migrations.AlterField(
            model_name='room',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(related_name='invited', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='profiles.Profile'),
        ),
    ]
