# Generated by Django 3.2.9 on 2022-02-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_rename_warning_review_warning_text'),
        ('rooms', '0015_auto_20220214_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invited', to='profiles.Profile'),
        ),
    ]
