# Generated by Django 3.2.9 on 2022-02-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_rename_warning_review_warning_text'),
        ('rooms', '0016_alter_room_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='profiles.Profile'),
        ),
    ]
