# Generated by Django 3.2.9 on 2022-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_auto_20220214_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='need_to_apply',
            field=models.BooleanField(default=True),
        ),
    ]
