# Generated by Django 3.2.9 on 2022-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_room_need_to_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='need_to_apply',
        ),
        migrations.AddField(
            model_name='room',
            name='no_apply',
            field=models.BooleanField(default=False),
        ),
    ]
