# Generated by Django 3.2.9 on 2022-03-02 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_room_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
