# Generated by Django 3.2.9 on 2022-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_alter_room_max_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
