# Generated by Django 3.2.9 on 2022-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_alter_room_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='default_room_image.png', null=True, upload_to='room_images/'),
        ),
    ]
